scrape_configs:
  - job_name: jenkins
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['jenkins-exporter:9118']
  - job_name: jenkins2
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['jenkins-exporter2:9103']
  - job_name: jenkins3
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['jenkins-exporter3:9118']